[rime-ls]
src.github = "wlh320/rime-ls"
fetch.github = "wlh320/rime-ls"
cargo_locks = ["Cargo.lock"]

[xdcmd]
src.github = "TransparentLC/xdcmd"
fetch.github = "TransparentLC/xdcmd"

[uuplugin-x86_64]
src.webpage = "https://router.uu.163.com/api/plugin?type=openwrt-x86_64"
src.regex = 'openwrt-x86_64/v([^/]*)/'
fetch.url = "https://uurouter.gdl.netease.com/uuplugin/openwrt-x86_64/v$ver/uu.tar.gz"

[uuplugin-aarch64]
src.webpage = "https://router.uu.163.com/api/plugin?type=openwrt-aarch64"
src.regex = 'openwrt-aarch64/v([^/]*)/'
fetch.url = "https://uurouter.gdl.netease.com/uuplugin/openwrt-aarch64/v$ver/uu.tar.gz"